- .eslintrc.yml
- package.json
- src/components/ConditionEditor/AndBlock.tsx
- src/components/ConditionEditor/Condition.tsx
- src/components/ConditionEditor/ConditionBlock.tsx
- src/components/ConditionEditor/ConditionSeparator.tsx
- src/components/ConditionEditor/OrBlock.tsx
- src/pages/ListPage/ListPage.tsx
- src/utils/ComponentUtils.tsx
- yarn.lock
Is not show anywhere and still dummy, but going to push early to focus on other things.
> Add condition builder presentation component

- profiles/local-frontend-and-api.js
- src/pages/AddCustomPolicyPage.tsx
- src/pages/ListPage/ListPage.tsx
This requires https://github.com/RedHatInsights/custom-policies-ui-backend/pull/5
> Adjust base path to conventions.

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- config/test.webpack.config.js
- Was using import syntax which js does not seem to like
> Fix build (on yarn start)

- .travis.yml
Testing the addition of an irc notification channel.
>  Testing the addition of an irc notification channel.

- .eslintrc.yml
- package.json
- src/components/Formik/Patternfly/Checkbox.tsx
- src/components/Formik/Patternfly/Common.ts
- src/components/Formik/Patternfly/FormSelect.tsx
- src/components/Formik/Patternfly/Switch.tsx
- src/components/Formik/Patternfly/TextInput.tsx
- src/components/Formik/Patternfly/index.ts
- src/components/Policy/ActionForm/ActionAlertForm.tsx
- src/components/Policy/ActionForm/ActionEmailForm.tsx
- src/components/Policy/ActionForm/ActionForm.tsx
- src/components/Policy/ActionForm/ActionFormProps.ts
- src/components/Policy/ActionsForm.tsx
- src/components/Policy/PolicyForm.tsx
- src/pages/AddCustomPolicyPage.tsx
- src/pages/ListPage/ListPage.tsx
- src/services/Api.ts
- src/types/Policy/Actions/Action.ts
- src/types/Policy/Actions/ActionAlert.ts
- src/types/Policy/Actions/ActionEmail.ts
- src/types/Policy/Actions/ActionSlack.ts
- src/types/Policy/Actions/ActionSms.ts
- src/types/Policy/Actions/ActionType.ts
- src/types/Policy/Actions/ActionWebhook.ts
- src/types/Policy/Actions/index.ts
- src/types/Policy/Policy.ts
- src/types/Policy/Severity.ts
- src/types/Policy/index.ts
- yarn.lock
Using [Formik](https://jaredpalmer.com/formik/) library to help updating the state of the form without having to do it manually.
Had to wrap some Patternfly components to adapt the onChange event as this was being used differently as regular input elements.
As a follow up I'll add validations using [Yup](https://github.com/jquense/yup)
> Use Formik to create the custom policy form

- src/components/Policy/PolicyForm.tsx
- src/config/Config.ts
- src/pages/ListPage/ListPage.tsx
- src/schemas/CreatePolicy/PolicySchema.ts
- src/services/Api.ts
- src/types/Policy/Policy.ts
UI-part of CPOL-32. Depends on https://github.com/RedHatInsights/custom-policies-ui-backend/pull/18 
> CPOL-32 Don't send customerid - backend takes it from x-rh-identity.

- src/components/Policy/PolicyTable.tsx
- src/components/Policy/TableToolbar/PolicyTableToolbar.tsx
- src/pages/ListPage/ListPage.tsx
- src/services/Api.ts
Depends on https://github.com/RedHatInsights/custom-policies-ui-backend/pull/19
> CPOL-42 Adds pagination to the custom policies list

- src/components/Policy/WizardSteps/ConditionsStep.tsx
> Provide an example that is valid.

- src/app/App.tsx
- src/components/AppSkeleton/AppSkeleton.tsx
- src/declarations/frontend-components.d.ts
This will present a Spinner until we get the user, ensuring that we only render if we are authenticated.
> CPOL-45 Waits for user before rendering the UI

- package.json
- src/app/App.tsx
- src/components/Policy/PolicyTable.tsx
- src/components/Policy/TableToolbar/PolicyTableToolbar.tsx
- src/components/Policy/WizardSteps/CreateCustomPolicyStep.tsx
- src/components/RbacContext.tsx
- src/config/Config.ts
- src/pages/ListPage/ListPage.tsx
- src/pages/ListPage/PolicyTableError.ts
- src/types/Rbac.ts
- src/utils/RbacUtils.ts
- yarn.lock
This is what it currently looks like when no permissions
~~I'll remove the rbac-client and test with the insights-chrome https://github.com/RedHatInsights/insights-chrome/pull/554 as a followup~~
I'll change when this is ready to test on ci
> CPOL-55 Support new RBAC

- src/components/Policy/ActionForm/ActionEmailForm.tsx
- src/components/Policy/ActionsForm.tsx
- src/components/Policy/WizardSteps/ActionsStep.tsx
- src/components/Policy/WizardSteps/ReviewStep.tsx
- src/schemas/CreatePolicy/Actions/ActionEmailSchema.ts
- src/schemas/CreatePolicy/PolicySchema.ts
- Remove additional fields
- Only one email action is valid
> CPOL-72 Email action doesn't have any parameter

- src/components/Policy/PolicyWizard.tsx
- src/components/Policy/PolicyWizardTypes.ts
- src/components/Policy/WizardSteps/ReviewStep.tsx
- src/pages/ListPage/CreatePolicyWizard.tsx
The error message is because the server had an internal server error.
> CPOL-62 Show error message when the policy creation failed

- src/components/Policy/PolicyWizard.tsx
- src/config/Config.ts
- src/pages/ListPage/CreatePolicyWizard.tsx
- src/pages/ListPage/DeletePolicy.tsx
- src/pages/ListPage/ListPage.tsx
- src/services/Api.ts
- src/types/Policy/Policy.ts
- src/utils/PolicyAdapter.ts
> CPOL-75 Allows to delete a single policy

- src/components/Policy/ActionsForm.tsx
- src/components/Policy/WizardSteps/ActionsStep.tsx
- src/components/Policy/WizardSteps/ConditionsStep.tsx
- src/components/Policy/WizardSteps/CreateCustomPolicyStep.tsx
- src/components/Policy/WizardSteps/DetailsStep.tsx
- src/components/Policy/WizardSteps/ReviewStep.tsx
- src/properties/Messages.ts
Not sure if banner titles work here. Perhaps a lighter gray color? 50% width?
> CPOL 58 : adding titles to wizard.

- src/components/Policy/PolicyWizard.tsx
- src/pages/ListPage/CreatePolicyWizard.tsx
- src/pages/ListPage/ListPage.tsx
- src/services/Api.ts
> CPOL-73 Allows to edit policies

- src/services/Api.ts
- src/types/Policy/Policy.ts
- src/utils/PolicyAdapter.ts
Use platform way of paging, where the data is inside a map as member 'data'.
Depends on https://github.com/RedHatInsights/custom-policies-ui-backend/pull/40
> CPOL-84 Use platform way of pagination.

- src/components/Policy/PolicyWizard.tsx
- src/components/Policy/PolicyWizardTypes.ts
- src/components/Policy/WizardSteps/ActionsStep.tsx
- src/components/Policy/WizardSteps/ConditionsStep.tsx
- src/config/Config.ts
- src/pages/ListPage/CreatePolicyWizard.tsx
- src/services/Api.ts
- src/utils/PolicyAdapter.ts
- Also prepares UI code for adding more server validation scenarios
i.e. name is not already used.
requires https://github.com/RedHatInsights/custom-policies-ui-backend/pull/44
> CPOL-81 Test Condition button now only validates the condition

- src/components/Policy/PolicyWizard.tsx
- src/components/Policy/PolicyWizardTypes.ts
- src/components/Policy/Table/PolicyTable.tsx
- src/components/Policy/TableToolbar/PolicyTableToolbar.tsx
- src/components/Policy/WizardSteps/CopyFromPolicy.tsx
- src/components/Policy/WizardSteps/CreateCustomPolicyStep.tsx
- src/hooks/index.ts
- src/hooks/usePolicyFilter.ts
- src/hooks/usePolicyPage.ts
- src/hooks/usePolicyRows.ts
- src/hooks/useSort.ts
- src/pages/ListPage/CreatePolicyWizard.tsx
- src/pages/ListPage/ListPage.tsx
- src/services/Api.ts
- src/types/Page.ts
- src/types/Policy/Policy.ts
- src/types/Policy/PolicyFilters.ts
- src/types/Policy/PolicyPaging.ts
- src/utils/PolicyAdapter.ts
> CPOL-77 Allows to copy a policy from the wizard

- src/components/Policy/TableToolbar/PolicyTableToolbar.tsx
> CPOL-96 Matches UXD for IsActive filter

- src/components/Policy/Table/ExpandedContent.tsx
- src/components/Policy/Table/PolicyTable.tsx
- src/properties/Messages.ts
>   CPOL-101 Change default messaging for some table entries.

- src/components/Policy/Table/PolicyTable.tsx
- src/hooks/usePolicyPage.ts
- src/pages/ListPage/ListPage.tsx
- src/pages/ListPage/PolicyTableError.ts
~~Depends on https://github.com/RedHatInsights/custom-policies-ui-frontend/pull/48 (merged)~~
> CPOL-95 Goes back to previous page when deleting every item on last page

- src/components/Policy/Table/PolicyTable.tsx
- src/components/Policy/WizardSteps/CopyFromPolicy.tsx
This connects something I forgot on CPOL-77
> CPOL-110 enables pagination on Wizard/copy of existing policy

- src/components/Policy/Table/PolicyTable.tsx
- src/pages/ListPage/ListPage.tsx
- src/pages/ListPage/PolicyTableError.ts
> Improves empty state

- src/pages/ListPage/ListPage.tsx
- src/types/Policy/Policy.ts
- src/utils/PolicyAdapter.test.ts
- src/utils/PolicyAdapter.ts
Depends on https://github.com/RedHatInsights/custom-policies-ui-backend/pull/50
> CPOL-92 Change policy id to UUID and use it also as trigger id

- src/components/Policy/Table/ActionsCell.tsx
- src/components/Policy/Table/ExpandedContent.tsx
- src/components/Policy/Table/ExpandedContent/Actions.tsx
- src/components/Policy/Table/PolicyTable.tsx
- src/utils/ComponentUtils.tsx
- src/utils/PolicyAdapter.test.ts
- src/utils/PolicyAdapter.ts
> CPOL-76 Show the actions in the policy list

- src/components/Formik/Patternfly/FormTextArea.tsx
- src/components/Formik/Patternfly/index.ts
- src/components/Policy/WizardSteps/DetailsStep.tsx
> CPOL-99 Use textarea for description field

- src/components/Policy/ActionForm/ActionWebhookForm.tsx
- src/components/Policy/Table/ExpandedContent/Actions.tsx
- src/schemas/CreatePolicy/Actions/ActionWebhookSchema.ts
- src/types/Policy/Actions/ActionWebhook.ts
- src/utils/PolicyAdapter.test.ts
- src/utils/PolicyAdapter.ts
> CPOL-121 Remove endpoint parameter from webhook

- src/components/Policy/ActionForm/ActionEmailForm.tsx
- src/components/Policy/ActionIcons.tsx
- src/components/Policy/ActionsForm.tsx
- src/components/Policy/Table/ActionsCell.tsx
- src/components/Policy/Table/ExpandedContent/Actions.tsx
- src/components/Policy/WizardSteps/ActionsStep.tsx
-  Only 1 email action or 1 hook
- Changed from button to dropdown
- Moved to top
- Some changes to the way each action is showed
> CPOL-113 UXD changes for "Add actions"

- src/components/Policy/Table/ExpandedContent/Actions.tsx
- src/components/Policy/Table/PolicyTable.tsx
- src/properties/Messages.ts
Remaining "Add Actions" button is taken care in #67
> CPOL-129 Using "Trigger actions" instead of "Actions" or "Run Actions"

- src/components/Policy/WizardSteps/CopyFromPolicy.tsx
- src/hooks/usePolicyRows.ts
- src/pages/ListPage/ListPage.tsx
> CPOL-125 Reset selection when loading or no policies are found

- src/components/Formik/Patternfly/FormText.tsx
- src/components/Formik/Patternfly/index.ts
- src/components/Policy/Table/ExpandedContent/Conditions.tsx
- src/components/Policy/WizardSteps/ReviewStep.tsx
- src/properties/Messages.ts
> CPOL-100 UXD changes on Wizard:Reviews

- src/components/Policy/PolicyWizard.tsx
- src/components/Policy/PolicyWizardFooter.tsx
- src/components/Policy/WizardSteps/ReviewStep.tsx
> Moved error to Wizard footer

- src/app/App.tsx
- src/app/AppContext.tsx
- src/components/EmailOptIn/EmailOptIn.tsx
- src/components/Policy/ActionForm/ActionEmailForm.tsx
- src/components/RbacContext.tsx
- src/config/Config.ts
- src/entry-dev.js
- src/entry.js
- src/hooks/usePromiseState.ts
- src/pages/ListPage/ListPage.tsx
- src/properties/Messages.ts
- src/services/Api.ts
- src/services/useUserSettingsEmailQuery.ts
- src/services/useUserSettingsQuery.ts
- src/types/UserSettings.ts
- src/utils/ApiUtils.ts
> CPOL-120 Add optin email message

- src/components/Policy/WizardSteps/ActionsStep.tsx
- src/properties/Messages.ts
> CPOL-126 Change remaining Webhook to Hook

- .travis.yml
- README.md
- package.json
- profiles/local-frontend-and-api.ts
- profiles/local-frontend.ts
- src/components/Policy/ActionForm/ActionEmailForm.tsx
- src/components/Policy/PolicyWizard.tsx
- src/config/Config.ts
- src/index.html
- src/pages/ListPage/ListPage.tsx
- src/properties/Messages.ts
- src/schemas/CreatePolicy/PolicySchema.ts
- src/types/GeneratedOpenApi.ts
- src/utils/RbacUtils.test.ts
- utils/openapi-generator/schemas/schemas.ts.handlebars
> CPOL-147 Rename project to "Policies"

- src/components/Policy/PolicyWizard.tsx
- src/components/Policy/WizardSteps/CreateCustomPolicyStep.tsx
- src/properties/Messages.ts
> POL-176 Remove remaining occurrences of "Custom policy" on wizard

- src/components/Formik/Patternfly/FormTextInput.tsx
- src/components/Policy/WizardSteps/ConditionsStep.tsx
- src/properties/Messages.ts
- Moved placeholder hint below
- Always show validate button
> POL-135, POL-180 Fixes on condition screen

- src/components/Policy/Table/PolicyTable.tsx
- src/components/Policy/TableToolbar/PolicyTableToolbar.tsx
- src/config/Config.ts
- src/pages/ListPage/CreatePolicyWizard.tsx
- src/pages/ListPage/ListPage.tsx
- src/services/Api.ts
- src/services/__tests__/useChangePolicyEnabled.test.ts
- src/services/__tests__/useSavePolicy.test.ts
- src/services/useChangePolicyEnabled.ts
- src/services/useSavePolicy.ts
- src/types/Policy/Policy.ts
edit: Updated gif; using the new enabled enpoint
~~I notice that having them sort by update time by default is kind of confusing when doing enable/disable as they are being pulled to the top.~~
> POL-152 Enable/Disable actions for policies

- src/components/Policy/Table/PolicyTable.tsx
- src/properties/Messages.ts
> POL-186 Last triggered -> Last evaluated

- jest.config.js
- src/components/Icons/DisabledPolicyIcon.tsx
- src/components/Icons/EnabledPolicyIcon.tsx
- src/components/Icons/index.ts
- src/components/Policy/ActionIcons.tsx
- src/components/Policy/Table/LastTriggeredCell.tsx
- src/components/Policy/TableToolbar/PolicyTableToolbar.tsx
- src/hooks/usePolicyFilter.ts
- src/hooks/usePolicyPage.ts
- src/pages/ListPage/ListPage.tsx
- src/types/Policy/PolicyPaging.ts
@katierik could you take a look at the gif?
> POL-187 Remove description filter and change isActive? to Enabled

- src/pages/ListPage/DeletePolicy.tsx
@katierik could you take a look at the screenshots? 
I forgot to ask how to show If deleting multiple policies, see what I'm currently doing.
> POL-196 Delete policy modal uses bold font for the name

- src/properties/Messages.ts
> POL-194 Change text for email warning on policy wizard

- src/components/Policy/ActionsForm.tsx
- src/components/Policy/WizardSteps/ActionsStep.tsx
- src/utils/Spacer.tsx
> POL-192 Change style for trigger action boxes

- src/schemas/CreatePolicy/PolicySchema.ts
> POOL-191 Change error message on empty condition

- src/properties/Messages.ts
> POL-178 Rename "Details" step to "Policy Details"

- src/components/Policy/ActionForm/ActionWebhookForm.tsx
- src/config/Config.ts
- src/properties/Messages.ts
> POL-166 Show hook details on wizard

- src/components/Policy/TableToolbar/PolicyTableToolbar.tsx
- src/components/Policy/WizardSteps/ReviewStep.tsx
- src/properties/Messages.ts
> POL-195 Change all "active" wording for enable/disable

- package.json
- src/components/Policy/EmptyState/Section.tsx
- src/components/Policy/PolicyWizard.tsx
- src/components/Policy/Table/PolicyTable.tsx
- src/hooks/usePolicyFilter.ts
- src/pages/ListPage/EmptyState.tsx
- src/pages/ListPage/ListPage.tsx
- src/pages/ListPage/PolicyTableError.ts
- src/properties/Messages.ts
- src/utils/ComponentUtils.tsx
- src/utils/Spacer.tsx
- yarn.lock
- No policies at all
- No policies when filtering
> POL-163 Update empty states on policies

- package.json
- src/components/Policy/TableToolbar/PolicyTableToolbar.tsx
- src/components/Policy/WizardSteps/CopyFromPolicy.tsx
- src/hooks/usePaginated.ts
- src/pages/ListPage/ListPage.tsx
- src/services/Api.ts
- src/services/Api/PaginatedActionBuilder.ts
- src/services/Api/__tests__/PaginatedActionBuilder.test.ts
- src/services/useGetPolicies.ts
- src/types/Page.ts
- src/utils/exporters/PolicyExporter/Base.ts
- src/utils/exporters/PolicyExporter/Csv.ts
- src/utils/exporters/PolicyExporter/Factory.ts
- src/utils/exporters/PolicyExporter/Json.ts
- src/utils/exporters/PolicyExporter/Type.ts
- src/utils/exporters/PolicyExporter/__tests__/Csv.test.ts
- src/utils/exporters/PolicyExporter/__tests__/Factory.test.ts
- src/utils/exporters/PolicyExporter/__tests__/Json.test.ts
- src/utils/exporters/PolicyExporter/__tests__/Type.test.ts
- yarn.lock
Depends ( includes) #90 
Requires https://github.com/RedHatInsights/policies-ui-backend/pull/89
> POL-174 Add export button (json and csv)

- src/app/App.tsx
- src/app/FetchingConfiguration.ts
- src/components/EmailOptIn/EmailOptIn.tsx
- src/components/Policy/ActionForm/ActionWebhookForm.tsx
- src/components/Policy/AddTriggersDropdown.tsx
- src/components/Policy/WizardSteps/ActionsStep.tsx
- src/components/Policy/__tests__/AddTriggersDropdown.test.tsx
- src/config/Config.ts
- src/utils/Insights.ts
- src/utils/__tests__/Insights.test.ts
- Assume is always there, as we wait for the value when loading the app
This simplifies some logic to make it more direct to use and test.
- Add tests for AddTriggersDropdown to ensure we only show hook in beta
- Also test other behavior in there
> POL-233 Simplify getInsights logic.

- src/components/Policy/Table/ExpandedContent/Usage.tsx
- src/config/Config.ts
- src/properties/Messages.ts
> POL-217 Adds link and changes wording on the dialog step

- src/components/Policy/PolicyWizard.tsx
- src/components/Policy/__tests__/PolicyWizard.test.tsx
- src/pages/ListPage/CreatePolicyWizard.tsx
- src/pages/ListPage/ListPage.tsx
- src/properties/Messages.ts
- src/utils/Insights.ts
- src/utils/__mocks__/Insights.ts
> POL-232 Wizard's name depends if we are creating new or editing

- .travis.yml
- codecov.yml
> Enable coverage reporting

- src/components/Policy/Table/ActionsCell.tsx
- src/properties/Messages.ts
The impl wasn't too difficult, but finding a way to automate testing on the ActionCells is tough. Maybe josejulio has a different take or just don't test the tooltip action?
>  POL-218: add tooltips to icons.

- config/setupTests.ts
- jest.config.js
- src/app/App.tsx
- src/app/AppContext.tsx
- src/app/__tests__/App.test.tsx
- src/app/useApp.ts
- src/components/Policy/EmptyState/Section.tsx
- src/pages/ListPage/ListPage.tsx
- src/pages/ListPage/PolicyTableError.ts
- src/pages/NoPermissions/NoPermissionsPage.tsx
- src/properties/Messages.ts
- src/services/__mocks__/useUserSettingsEmailQuery.ts
- src/utils/__mocks__/Insights.ts
- src/utils/__mocks__/RbacUtils.ts
- src/utils/__tests__/Insights.test.ts
- test/AppWrapper.tsx
> POL-172 No RBAC permission empty state

- src/components/Policy/WizardSteps/CreatePolicyStep.tsx
@josejulio, How is this? Also, do we have a recommended way to append various values to classname for various react component? This way works but it is brittle. I tried using 'classnames/bind' but got stuck battling random compilation and typescript issues and backed it out.
>  POL-177: Update with PF spacing.

- .github/workflows/ExpressionInSync.yml
- package.json
- src/utils/Expression/ExpressionLexer.ts
- src/utils/Expression/ExpressionListener.ts
- src/utils/Expression/ExpressionParser.ts
- src/utils/Expression/ExpressionVisitor.ts
The purpose is to check if the Expression.g4 file has changed and we need to update our local files.
This check is out of the main check to avoid it failing the whole build while keeping it visible. So we know it fails, and we can update it on a separate PR.
> Check if engine's Expression file has changed

- package.json
- src/utils/PolicyAdapter.ts
- src/utils/__tests__/PolicyAdapter.test.ts
> POL-279 Parse the lastTriggered value correctly.

- src/pages/ListPage/CreatePolicyWizard.tsx
- src/pages/ListPage/__tests__/CreatePolicyWizard.test.tsx
- Removed line 0
- From "position x" to "position x+1".
position 0 turns into position 1
Depends on #122
> POL-223 Changed the condition error message 

- package.json
- yarn.lock
This fixes an issue with firefox not supporting some features used by that lib
> POL-281 Downgrade camelcase lib

- src/components/Policy/PolicyWizard.tsx
- src/pages/ListPage/CreatePolicyWizard.tsx
- src/pages/ListPage/__tests__/CreatePolicyWizard.test.tsx
- src/utils/__mocks__/AlertUtils.ts
> POL-231 Show a better message when trying to edit a deleted policy

- src/pages/PolicyDetail/PolicyDetail.tsx
- src/pages/PolicyDetail/__tests__/PolicyDetail.test.tsx
> POL-289 Fixes loading on the trigger history

- src/index.html
Accidentally pushed the `beta` on a previous PR
> Fix: Revert back some changes that were meant only for dev

- .travis/custom_release.sh
master -> {ci|qa}-{stable|beta}
prod -> prod-{stable-beta}
Keeping the release branch in case we want to do test something on
a specific env.
> Put back our original release schema:

- src/components/Trigger/TableToolbar.tsx
- src/components/Trigger/__tests__/TableToolbar.test.tsx
- src/generated/ActionCreators.ts
- src/pages/PolicyDetail/PolicyDetail.tsx
- src/pages/PolicyDetail/__tests__/PolicyDetail.test.tsx
- src/pages/PolicyDetail/hooks/useGetAllTriggers.ts
- src/pages/PolicyDetail/hooks/useGetPolicyDetailTriggerHistory.ts
- src/pages/PolicyDetail/hooks/useTriggerFilter.ts
- src/pages/PolicyDetail/hooks/useTriggerPage.ts
- src/services/useGetPolicyTriggers.ts
> POL-301 Adds server side policy history filtering

- src/pages/ListPage/ListPage.tsx
- src/pages/ListPage/PolicyTableError.ts
- Shows "unable to process request"
> POL-322 Show an error message when the server is down

- src/components/Trigger/Table.tsx
- src/components/Trigger/__tests__/Table.test.tsx
- src/generated/ActionCreators.ts
- src/pages/PolicyDetail/PolicyDetail.tsx
- src/pages/PolicyDetail/__tests__/PolicyDetail.test.tsx
> POL-302 Add sorting for date and system name (policy history)

- package.json
- src/pages/PolicyDetail/Skeleton.tsx
- yarn.lock
- Upgrade frontend-components
- Warning for not using BreadcrumbItem inside a Breadcrumb
> Remove some console warnings

- src/components/Trigger/TableToolbar.tsx
- src/components/Trigger/__tests__/TableToolbar.test.tsx
- src/pages/PolicyDetail/PolicyDetail.tsx
- src/pages/PolicyDetail/__tests__/PolicyDetail.test.tsx
- src/pages/PolicyDetail/hooks/useTriggerPage.ts
> POL-326 Fix pagination controls as per the UXD - Tables doc

- .gitignore
- README.md
- package.json
- src/cli/pushhost.ts
- yarn.lock
> Adds command to generate a varied trigger history for manual testing

- src/pages/PolicyDetail/PolicyDetail.tsx
- src/pages/PolicyDetail/Skeleton.tsx
- src/pages/PolicyDetail/TriggerDetailSection.tsx
- src/pages/PolicyDetail/TriggerErrorState.tsx
- src/pages/PolicyDetail/__tests__/PolicyDetail.test.tsx
- src/properties/Messages.ts
Previously it was showing a message saying that there is not
history for the given policy
> Shows error when a policy fails to load.

- src/pages/PolicyDetail/PolicyDetail.tsx
- src/pages/PolicyDetail/__tests__/PolicyDetail.test.tsx
- src/properties/Messages.ts
- test/AppWrapper.tsx
> POL-334 Show error message when server returns an error

- src/components/Trigger/Filters.ts
- src/components/Trigger/TableToolbar.tsx
- src/components/Trigger/__tests__/TableToolbar.test.tsx
- src/pages/PolicyDetail/hooks/__tests__/useTriggerPage.test.ts
- src/pages/PolicyDetail/hooks/useTriggerFilter.ts
- src/pages/PolicyDetail/hooks/useTriggerPage.ts
> POL-336 Remove trigger history id filter

- package.json
- src/config/Config.ts
- src/hooks/__tests__/usePolicyPage.test.tsx
- src/hooks/usePolicyPage.ts
- src/pages/ListPage/ListPage.tsx
- src/pages/ListPage/__tests__/ListPage.test.tsx
- src/pages/PolicyDetail/TriggerDetailSection.tsx
- src/pages/PolicyDetail/__tests__/PolicyDetail.test.tsx
- test/SmokeTest.tsx
- yarn.lock
Changes from 50 to 20 in Policy list and trigger history pages.
> POL-340 Tables should have 20 elements by default

- jest.config.js
- src/components/Condition/Tokens.ts
- src/hooks/__tests__/useFacts.ts
- src/utils/exporters/Policy/__tests__/Factory.test.ts
- src/utils/exporters/Trigger/__tests__/Factory.test.ts
- Adds tests to cover remaining cases in exporters/*/Factory
- Remove Tokens.ts
- Tests for useFacts
- Remove from coverage report the cli tools
> Tests and remove unused file

- package.json
Unintentionally disabled on previous travis.yml change
> Add back codecov reporting on ci

- src/components/Policy/AddTriggersDropdown.tsx
- src/components/Policy/__tests__/AddTriggersDropdown.test.tsx
> Remove hooks from beta

- src/components/Trigger/Table.tsx
> POL-346 Ensure the date doesn't wrap and the hostname wraps and breaks

- src/pages/PolicyDetail/TriggerEmptyState.tsx
- src/pages/PolicyDetail/__tests__/TriggerEmptyState.test.tsx
- src/properties/Messages.ts
> POL-345 Add retention info for triggers history

- package.json
- src/pages/CreatePolicyWizard/CreatePolicyWizard.tsx
- src/pages/CreatePolicyWizard/__tests__/CreatePolicyWizard.test.tsx
- src/pages/ListPage/hooks/useToolbarActions.ts
- yarn.lock
Updated text for specified toast alerts. Still need to implement new alerts.
> POL-510 Updated toast alert text

- package.json
- yarn.lock
- Remember to merge using the `Merge pull request/Create a merge commit` method and using `Prod update (Merge)` as commit title.
- Wait until branches `prod` and `prod-beta` from https://github.com/RedHatInsights/policies-ui-frontend-build repository are updated.
- Trigger the deployment in jenkins.
See prod deployment for more info.
> Prod update

- .github/workflows/OpenAPIInSync.yml
- .travis.yml
- Removes them from regular PRs
- Uses it for prod PRs to check with current prod
- Removes it from prod builds
> Updates openapi check

- src/components/Policy/Table/PolicyTable.tsx
- src/components/Trigger/Table.tsx
> POL-487 Sticky headers for all tables

- src/pages/CreatePolicyWizard/CreatePolicyWizard.tsx
> POL-641 Better error message when a name is invalid

- src/components/Policy/Table/PolicyTable.tsx
- src/hooks/usePolicyPage.ts
> POL-453 Sort by last triggered time

- src/config/Config.ts
Replaces https://github.com/RedHatInsights/policies-ui-frontend/pull/349
> update docs versions for Insights, Console, Cost & Subscriptions

- src/properties/Messages.ts
CRCFEEDBK-2379 Fix missing quote on example
> CRCFEEDBK-2379 Fix missing quote on example

- config/prod.webpack.config.ts
Adds the deployment tag necessary for containers to build appropriate assets
> fix(webpack): Updates the webpack with deployment tag

- config/prod.webpack.config.ts
This reverts commit d5ec7ce56897fb9906d60d8e2d59de8c5841d83b.
> Revert "fix(webpack): Updates the webpack with deployment tag"

- src/config/Config.ts
Updates the doc links with new 1-latest subpath
> chore(RHINENG-7106): update doc links with 1-latest

- yarn.lock
https://issues.redhat.com/browse/RHINENG-9005
> chore(deps): RHINENG-9005: Bump `follow-redirects` to fix a CVE

- yarn.lock
https://issues.redhat.com/browse/RHINENG-9522
> chore(deps): Bump `webpack-dev-middleware` to fix a CVE

- package.json
- yarn.lock
> chore(deps): RHINENG-8452 - update frontend-components

- package.json
- yarn.lock
https://issues.redhat.com/browse/RHINENG-10864
> chore: Update `karma` to fix a CVE

- src/pages/CreatePolicyWizard/CreatePolicyWizard.tsx
Fixes the missing spacer in front of the link.
> fix(notification): Add missing spacer when creating a new policy

- src/pages/ListPage/ListPage.tsx
https://issues.redhat.com/browse/RHINENG-14772
> feat(Header): Add info popover to Policies list header

- .gitmodules
- .tekton/policies-ui-frontend-pull-request.yaml
- .tekton/policies-ui-frontend-push.yaml
[RHINENG-16160](https://issues.redhat.com/browse/RHINENG-16160)
> chore(build): use shared Dockerfile
