RedHatInsights/policies-ui-frontend

- package.json
- profiles/local-frontend-and-api.js
- src/pages/AddCustomPolicyPage.tsx
- src/pages/ListPage/ListPage.tsx
Configures the proxy to map requests from `/api/v1/policies` to ``http://localhost:8080/api/v1/policies`
> Use the local proxy when reaching the backend

- src/components/Policy/PolicyWizard.tsx
- src/components/Policy/PolicyWizardFooter.tsx
- src/components/Policy/PolicyWizardTypes.ts
- src/components/Policy/WizardSteps/ActionsStep.tsx
- src/components/Policy/WizardSteps/ConditionsStep.tsx
- src/components/Policy/WizardSteps/CreateCustomPolicyStep.tsx
- src/components/Policy/WizardSteps/DetailsStep.tsx
- src/components/Policy/WizardSteps/ReviewStep.tsx
- src/components/Policy/WizardSteps/WizardStepExtended.ts
- src/pages/ListPage/CreatePolicyWizard.tsx
- src/services/Api.ts
- src/utils/PFColors.ts
- Hooks a validation (Test condition) button for the
conditions step that blocks until the conditions
are valid.
- Bug fix to the WizardPolicy, extracts FormikBinding
Compontent to avoid re-creation on render, this caused
several problems: unecesary renders, validations, and
invalid state in the validations.
Also fixes CPOL-54 (because of the bug fix)
When the error is unknow, currently showing the response or if none: `Unknown Error when trying to validate: (Code ${res.status})`
> CPOL-57 Validate the conditions with the ui-backend

- src/app/App.tsx
- src/app/FetchingConfiguration.ts
- src/components/Policy/ActionsForm.tsx
- src/utils/Insights.ts
Depends on #39, Updated part of that code to use the Insights type.
> CPOL-79 Removes the Webhook action when in `beta`

- src/app/App.tsx
- src/app/FetchingConfiguration.ts
- src/components/Policy/ActionsForm.tsx
- src/utils/Insights.ts
- Using a promise to ensure we have a value before resolving
Without this, we intermittently get between loads "insights is not defined" error in the console.
> Ensure `insights` var binds correctly

- profiles/local-frontend-and-api.ts
This makes the proxy more reliable when on development.
I'm using a bigger timeout and tested with lower values to ensure it fails in the same way as it occasionally happens to me.
> Increase timeout when using insights-proxy

- src/services/Api.ts
- src/services/__tests__/Api.test.ts
- src/services/__tests__/useSavePolicy.test.ts
- Adds tests for API.createAction
- Supports URL with queryParams
- Returns URLs without trailing '?'
> Changes in API.createAction

- profiles/local-frontend-and-api.ts
(When using the proxy for development)
> Route all the /api/policies/ requests to localhost

- src/pages/ListPage/ListPage.tsx
- src/properties/Messages.ts
- Fixes double space
Ignore the title, that's covered in #97
> POL-193 Change text for email warning on landing page

- package.json
- src/hooks/__tests__/usePaginated.test.tsx
- src/hooks/usePaginated.ts
- src/pages/ListPage/ListPage.tsx
- src/pages/ListPage/__tests__/useGetListPagesPolicies.test.tsx
- src/pages/ListPage/__tests__/useGetListPagesPolicies.tsx
- src/pages/ListPage/useGetListPagePolicies.ts
- src/services/useGetPolicies.ts
- src/types/Page.ts
- src/utils/ApiUtils.ts
- yarn.lock
This is to truly know at a given time if the user has more elements in case a filtered search yields 0 elements, to be able to show which empty state to show (you have no policies or no policies match the filter) and for knowing if we want to show the "copy from policy" option in the wizard.
- Also adding fetch-mock library (for mocking network requests)
>  POL-250 Implemented smart query into our list page to know if we have more elements or not

- .github/scripts/commands.sh
It wasn't transforming the `<script type="text/javascript" src="/beta/apps/policies/js/vendor.js"></script>` into `<script type="text/javascript" src="/apps/policies/js/vendor.js"></script>`
Tested locally by doing:
1. `yarn build:prod`
2. Including commands `source .github/scripts/commands.sh`
3. `ensure_beta`
4. Inspecting contents of `dist/index.html`, all `src` there should start with `/beta/apps`
5. `ensure_stable`
4. Inspecting contents of `dist/index.html`, all `src` there should start with `/apps`
On ci, testing by inspecting the source code the index for stable [1] and beta [2].
For beta it should have:
1. `<base href="/beta/"/>`
2. `src="/beta/apps/policies/js/vendor.js"`
3. `src="/beta/apps/policies/js/App.js"`
For stable it should have:
1. `<base href="/"/>`
2. …
> POL-285 Relax expression to turn script's src also

- src/components/Policy/Table/PolicyTable.tsx
We have no way to sort by last triggered column, it was sorting by isEnabled.
Since its confusing (hence the bug), we can remove the ability to sort by that field (we already have the filtering) until we can actually sort by that column.
Before:
After:
> POL-288 Remove sorting on last triggered column

- src/Routes.tsx
- src/pages/Error/Page.tsx
- src/pages/Error/__tests__/Page.test.tsx
- src/properties/Messages.ts
- src/utils/ComponentUtils.tsx
- test/AppWrapper.tsx
I manually added some errors for this gif, but we have seen events when nothing is rendered in the app (only insights chrome is show)
> Adds error boundary to avoid blank pages on error

- src/pages/PolicyDetail/PolicyDetail.tsx
Extends the optional chaining to the data field, if anything in the chain is undefined, return undefined (this is true when we are fetching the data)
> POL-313 Check if payload.data is undefined

- src/components/Policy/TableToolbar/PolicyTableToolbar.tsx
- src/components/Policy/WizardSteps/CopyFromPolicy.tsx
- src/pages/ListPage/ListPage.tsx
The table in the wizard remains unchanged:
> POL-327 Adding full pagination component at the bottom

- src/hooks/useTextFormat.tsx
- src/pages/PolicyDetail/ErrorState.tsx
- src/pages/PolicyDetail/PolicyDetail.tsx
- src/pages/PolicyDetail/TriggerDetailSection.tsx
- src/pages/PolicyDetail/TriggerErrorState.tsx
- src/pages/PolicyDetail/__tests__/ErrorState.test.tsx
- src/properties/Messages.ts
@katierik I've changed these errors in response to your comment on https://github.com/RedHatInsights/policies-ui-frontend/pull/192#issuecomment-666393306
> Changing some errors messages

- src/components/Policy/ActionForm/ActionForm.tsx
- src/components/Policy/ActionForm/ActionNotificationForm.tsx
- src/components/Policy/ActionIcons.tsx
- src/components/Policy/ActionsForm.tsx
- src/components/Policy/AddTriggersDropdown.tsx
- src/components/Policy/Table/ActionsCell.tsx
- src/components/Policy/Table/ExpandedContent/Actions.tsx
- src/components/Policy/__tests__/AddTriggersDropdown.test.tsx
- src/config/Config.ts
- src/generated/ActionCreators.ts
- src/properties/Messages.ts
- src/schemas/CreatePolicy/Actions/ActionNotificationSchema.ts
- src/schemas/CreatePolicy/Actions/ActionWebhookSchema.ts
- src/schemas/CreatePolicy/Actions/__tests__/ActionEmailSchema.test.ts
- src/schemas/CreatePolicy/Actions/__tests__/ActionWebhookSchema.test.ts
- src/schemas/CreatePolicy/Actions/index.ts
- src/schemas/CreatePolicy/PolicySchema.ts
- src/schemas/CreatePolicy/__tests__/PolicySchema.test.ts
- src/types/Policy/Actions/Action.ts
- src/types/Policy/Actions/ActionNotification.ts
- src/types/Policy/Actions/ActionType.ts
- src/types/Policy/Actions/ActionWebhook.ts
- src/types/Policy/Actions/__tests__/Action.test.ts
- src/types/Policy/Actions/index.ts
- src/types/adapters/PolicyAdapter.ts
- src/types/adapters/__tests__/PolicyAdapter.test.ts
- src/utils/exporters/Policy/__tests__/Csv.test.ts
- Does not break if ui-backend still has "webhook", silently ignores it.
> Switch webhook to notifications

- package.json
- yarn.lock
This bug was caused by a bug in [openapi2typescript](https://github.com/RedHatInsights/insights-common-typescript/pull/51)
> Fix email subscribed bug by updating

- src/components/Policy/AddTriggersDropdown.tsx
- src/components/Policy/__tests__/AddTriggersDropdown.test.tsx
Updating like this in case we need to push something to prod, when we are ready to push notifications to prod-beta I'll update it.
> Show notification action on [ci|qa|stage]-beta but not on prod-beta

- package.json
- src/app/useApp.ts
- yarn.lock
- update FEC webpack config: fixes singleton issue with redux
- remove history push after app unmounts
- the return function from the useApp hooks is called after the app unmounts and it adds a listener on the chrome nav changes
- the history change mutates the URL of other apps after you navigate to the from policies
cc @josejulio
> Fix lingering history changes after unmount

- src/pages/ListPage/ListPage.tsx
- test/AppWrapper.tsx
This moves around the logic for whats displayed regarding zero state. Mocks : https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/a/qbe9Ol2#Inspect 
Table page is unaffected : 
ZeroState no longer displays "Policies" Title up top
This page is unaffected:
>  fix(ZeroState): Update zero state according to updated mocks

- src/pages/ListPage/ListPage.tsx
As requested per UX team, this adds an id so that the button on zero state page can be tracked.
> Add ID to ZeroState for tracking

- config/prod.webpack.config.ts
This hopefully fixes the policies app on staging env by passing correct deployment target into webpack
> chore(RHINENG-501): add proper deployment check in prod webpack config

- src/Routes.tsx
- src/__tests__/Routes.test.tsx
This refactor is needed according to the official migration guide
Here is a link to the relevant section:
https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-router-v51 
What does this PR include ? 
- Refactor of InsightsRoute
https://reactrouter.com/en/main/upgrading/v5#refactor-custom-routes
- Convert Redirect to Route inside a Switch
https://reactrouter.com/en/main/upgrading/v5#remove-redirects-inside-switch
> Refactor Custom Route Component 'InsightsRoute' Before Upgrading to React Router v6

- src/components/Policy/PolicyWizard.tsx
- src/components/Policy/__tests__/PolicyWizard.test.tsx
This just adds an ouiaId to the policy wizard.
To test, just inspect the page and check the page for pendo-policy-wizard in a ctrl+f. 
Verify that its not there
Then open the policy wizard and see that the id populates and that it points to the entire wizard
> chore(RHINENG-7853): Add OUIA id to create Policy wizard

- jest.config.js
- package.json
- yarn.lock
Fixes https://issues.redhat.com/browse/RHINENG-8636 by updating the Axios to ^1.6.8. I have tested the application against breaking changes, did not spot any.
> chore(RHINENG-8636): update axios to ^1.6.8

- src/pages/ListPage/ListPage.tsx
- src/pages/NoPermissions/NoPermissionsPage.tsx
- src/pages/PolicyDetail/PolicyDetail.tsx
- src/pages/PolicyDetail/Skeleton.tsx
Removes this error from the console
> chore: Remove deprecated `Main` component

- src/Routes.tsx
- src/__tests__/Routes.test.tsx
- src/pages/Error/Page.tsx
- src/pages/PolicyDetail/hooks/usePolicy.ts
- test/AppWrapper.tsx
- Change 'react-router' to 'react-router-dom' -- 'react-router' is a subset of 'react-router-dom' which works with react-native as well and we shouldn't use it
- Remove the unused props from `ErrorPageInternal` along with removal of `withRouter`
> Tweaks to prepare for react-router-dom v6 migration

- src/components/Policy/Table/PolicyTable.tsx
Fixes Policy table sorting.
Before:
```
chrome-root.93304c665f98ee3b.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'defaultDirection')
```
[Screencast from 2024-10-02 12-38-35.webm](https://github.com/user-attachments/assets/52f29195-1092-4703-aa3c-f7709777a6bb)
After:
[Screencast from 2024-10-02 12-38-54.webm](https://github.com/user-attachments/assets/80191b15-10ef-4ceb-9358-df72f6ac85d1)
> fix(RHINENG-13389): Fix Policies table sorting
